spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:library-dev;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true

logging:
  file:
    name: ${LOG_DIR:logs}/library-dev.log
